server:
  servlet:
    context-path: /testWar
  ssl:
    key-store: classpath:localhost.jks
    key-store-password: changeit
    keyStoreType: JKS
    key-alias: localhost
    #    client-auth: need
    trust-store: classpath:localhost.jks
    trust-store-password: changeit
    trust-store-provider: SUN
    trust-store-type: JKS
    client-auth: need
spring:
  application:
    name: testWar
